ingress:
  hostname: chemscraper.backend.staging.mmli2.ncsa.illinois.edu
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: staging-cors-header@kubernetescrd

config:
  enableGPU: true
  runtimeClassName: nvidia
